### ISSUE TITLE
meteor add contribute:image-watermark does not work (returns error: no such package)

### ISSUE THREAD

**Issue by cypa1** [newbiepub/meteor-image-watermark#1]

**Comment by newbiepub** [comment]
Sorry about this. I haven't update file README.MD. This should work : meteor add newbiepub:image-watermark . 
p/s : I just not publish this package to atmospherejs. So if you want to use it, you can pull it to packages folder in your meteor application.

**Comment by cypa1** [comment]
Yeah, already did that.
